apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  labels:
    app: userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      restartPolicy: Always
      containers:
      - name: userjava
        image: registryukc4468.azurecr.io/user-java:1.0
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: env-cm
          - secretRef:
              name: db-info
