apiVersion: v1
kind: Service
metadata:
  name: userjava-service
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: userjava
  ports:
  - protocol: TCP
    port: 80